steps:
  # Langkah 0: Membuat file service account key.json
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "${_SERVICE_ACCOUNT_KEY}" > /workspace/ide-kita-5683f0576850.json
        echo "${_FIREBASE_SERVICE_ACCOUNT}" > /workspace/firebase-adminsdk-ltd4t-64bcc1cae5.json

  # Langkah 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia.gcr.io/ide-kita/backend-idekita:1.0", "."]

  # Langkah 2: Push image Docker ke Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/ide-kita/backend-idekita:1.0"]

  # Langkah tambahan: Menampilkan isi direktori /app
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ls -la /workspace
        cat /workspace/firebase-adminsdk-ltd4t-64bcc1cae5.json

  # Langkah 3: Deploy aplikasi ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "backend"
      - "--image"
      - "asia.gcr.io/ide-kita/backend-idekita:1.0"
      - "--platform"
      - "managed"
      - "--region"
      - "asia-southeast2"
      - "--allow-unauthenticated"
      - "--port"
      - "8000"
      - "--update-env-vars"
      - "DB_NAME=$_DB_NAME,DB_USERNAME=$_DB_USERNAME,DB_PASSWORD=$_DB_PASSWORD,DB_HOST=$_DB_HOST"
